<a href="https://colab.research.google.com/github/sizah123/Big_Data/blob/pfe/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
# Run and print a shell command.
def run(cmd):
  print('>> {}'.format(cmd))
  !{cmd}
  print('')

run('pip install --upgrade pip')

# Install apache-beam.
run('pip install --quiet apache-beam')

>> pip install --upgrade pip
Requirement already satisfied: pip in /usr/local/lib/python3.10/dist-packages (24.2)

>> pip install --quiet apache-beam

In [12]:
from google.colab import files
uploaded = files.upload()

Saving users_v (1).csv to users_v (1) (1).csv

In [13]:
!pip install pandas
import pandas as pd # Make sure to import pandas and assign it to pd

df = pd.read_csv('users_v (1).csv')
df.head()

Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

,user_id,name,gender,age,address,date_joined
0,1,Anthony Wolf,male,73,New Rachelburgh-VA-49583,2019/03/13
1,2,James Armstrong,male,56,North Jillianfort-UT-86454,2020/11/06
2,3,Cody Shaw,male,75,North Anne-SC-53799,2004/05/29
3,4,Sierra Hamilton,female,76,New Angelafurt-ME-46190,2005/08/26
4,5,Chase Davis,male,31,South Bethmouth-WI-18562,2018/04/30

In [16]:
#question 1
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
import csv
from datetime import datetime


def format_date(date_str):
    try:
        # Attempt to parse the date in the format 'YYYY/MM/DD'
        return datetime.strptime(date_str, '%Y/%m/%d').strftime('%Y-%m-%d')
    except ValueError:
        # If the date format is different, you can add more cases or raise an error
        raise ValueError(f"Date format for '{date_str}' not recognized.")


# Function to process the rows
def process_row(row):
    fields = next(csv.reader([row]))
    user_id, name, gender, age, address, date_joined = fields

    # Split address and handle cases with missing parts
    address_parts = address.split(',')
    city = address_parts[0].strip() if len(address_parts) > 0 else ''
    state = address_parts[1].strip() if len(address_parts) > 1 else ''
    zip_code = address_parts[2].strip() if len(address_parts) > 2 else ''

    # Format the address correctly
    formatted_address = f"{city}, {state}, {zip_code}".strip(', ')

    # Reformat the date
    formatted_date = format_date(date_joined)

    # Change gender from abbreviation to full form
    gender = "Female" if gender == 'F' else "Male"

    return f"{user_id}; {name}; {gender}; {age}; {formatted_address}; {formatted_date}"

# Beam Pipeline for task 1
def run_pipeline():
    pipeline_options = PipelineOptions()
    with beam.Pipeline(options=pipeline_options) as p:
        input_data = (p
                      | 'Read CSV File' >> beam.io.ReadFromText('users_v (1).csv', skip_header_lines=1)
                      | 'Process Rows' >> beam.Map(process_row)
                     # | 'Write to CSV' >> beam.io.WriteToText('marketing_format.csv', file_name_suffix='.csv', shard_name_template='')
                      | 'Print Results' >> beam.Map(print))

if __name__ == '__main__':
    run_pipeline()

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['-f', '/root/.local/share/jupyter/runtime/kernel-f060438b-38b1-4479-ad13-51b9f09726b6.json']

1; Anthony Wolf; Male; 73; New Rachelburgh-VA-49583; 2019-03-13
2; James Armstrong; Male; 56; North Jillianfort-UT-86454; 2020-11-06
3; Cody Shaw; Male; 75; North Anne-SC-53799; 2004-05-29
4; Sierra Hamilton; Male; 76; New Angelafurt-ME-46190; 2005-08-26
5; Chase Davis; Male; 31; South Bethmouth-WI-18562; 2018-04-30
6; Sierra Andrews; Male; 21; Ryanville-MI-69690; 2007-05-25
7; Ann Stone; Male; 41; Smithmouth-SD-17340; 2005-01-05
8; Karen Santos; Male; 34; Mariaville-AK-29888; 2003-12-12
9; Ronald Meyer; Male; 41; North Cherylhaven-NJ-04197; 2015-11-14
10; Steven Rivera; Male; 43; Wayneside-VT-29040; 2003-05-15
11; Cameron White; Male; 67; Port Stephanie-ME-08721; 2003-10-15
12; Anna Glenn; Male; 73; Lake Pamela-NY-61706; 2013-09-27
13; Kenneth Martinez; Male; 21; West Kimberly-AZ-87210; 2002-03-13
14; David Love; Male; 59; Hernandezland-KY-97361; 2020-12-26
15; Timothy Jones; Male; 68; Wilsonport-MT-95064; 2015-11-13
16; Christopher Hayden; Male; 48; Sandraborough-CT-85036; 2017-07-12
17; Mikayla Jacobson; Male; 67; Harrisonhaven-ID-71589; 2005-02-23
18; Steven Myers; Male; 72; North Christinaside-ME-79432; 2008-08-09
19; Justin Beasley; Male; 50; Whiteport-GA-29233; 2000-08-09
20; Stephanie Mclaughlin; Male; 40; Martinezton-MT-27123; 2014-05-18
21; Heather Bryant; Male; 57; South William-OR-58777; 2002-02-22
22; Mark Garcia; Male; 23; North Natalie-AR-68761; 2006-04-11
23; Stephanie Williamson; Male; 22; Brittanyton-DC-24346; 2003-03-09
24; Patrick Jackson; Male; 38; Cassandrafort-NC-38748; 2019-03-07
25; Mrs. Michele Fuller; Male; 29; Taylorhaven-CT-97167; 2010-11-14
26; Shirley Lucas; Male; 50; East Chaseside-MA-11637; 2006-12-26
27; Kenneth Montgomery; Male; 55; South Christinemouth-SC-54543; 2000-06-20
28; Kathryn Ibarra; Male; 30; New Sean-OH-37054; 2016-02-03
29; Joseph Nelson; Male; 24; Phamside-OR-38312; 2004-07-30
30; Douglas Greer; Male; 60; East Sandraview-ND-01119; 2003-05-06
31; James Lewis; Male; 77; Cummingsville-DC-95378; 2000-09-10
32; Michael Chapman; Male; 60; Powellside-SC-98573; 2016-04-10
33; Andrew Watkins; Male; 45; Terrellchester-NM-38781; 2007-10-10
34; Kimberly Rice; Male; 61; Griffinmouth-OH-05467; 2019-12-22
35; Cheryl Holt; Male; 32; Adamside-HI-99291; 2016-02-25
36; Brandon White; Male; 42; Jennifershire-CA-09827; 2004-06-21
37; Edward Martin; Male; 19; Annettechester-CO-34375; 2011-11-26
38; Lindsay Brown; Male; 29; Fraziermouth-NH-60888; 2020-05-05
39; Kevin Rose; Male; 30; East Josephport-DE-13217; 2007-06-07
40; Fernando Watts; Male; 31; Rodriguezside-VA-84198; 2016-07-27
41; Joshua Quinn; Male; 62; Emilytown-NM-68576; 2005-08-01
42; Alexandria Taylor; Male; 48; Brewerhaven-MT-66936; 2014-11-15
43; Regina Ross; Male; 50; North Anaburgh-WI-72723; 2006-02-16
44; Gerald Boone; Male; 60; Connieland-HI-26467; 2018-11-06
45; James Huang; Male; 68; Port Brittanyburgh-SC-02871; 2004-07-12
46; Stephanie Wallace; Male; 58; South Bradley-NC-09847; 2012-03-22
47; Cody Lynch; Male; 71; Lake Alison-WY-16868; 2016-03-12
48; Samuel Reeves; Male; 74; North Kimberly-WI-68170; 2009-08-31
49; Steve Oneill; Male; 26; North Jimmy-ME-90116; 2017-01-09
50; Mr. Ruben Durham; Male; 19; Sanchezstad-WA-55213; 2007-12-30
51; Sarah Delgado PhD; Male; 59; West Jenniferfort-OK-42974; 2000-01-17
52; Ashlee Beck; Male; 51; Lake Lindaside-OR-78900; 2008-11-17
53; Steve Brooks; Male; 20; Lopezmouth-IN-58269; 2004-07-30
54; Sandra Barnes; Male; 64; Lake Thomas-VT-24520; 2001-06-09
55; Richard Morris; Male; 79; Williammouth-AR-88280; 2017-12-22
56; Phillip Andrade; Male; 34; Stevenhaven-OR-75070; 2007-07-27
57; Gregory Harris; Male; 18; New John-CT-68844; 2000-12-16
58; Jerry Jones; Male; 61; Sarahborough-VA-16710; 2001-07-24
59; Denise Wade; Male; 24; Aliceville-AL-17290; 2021-01-05
60; Elizabeth Williams; Male; 63; West Tyler-WI-04103; 2013-04-29
61; Jessica Sanders; Male; 64; North Madison-NV-91433; 2010-10-09
62; James Ward; Male; 75; East Brandonside-UT-50896; 2009-11-28
63; Timothy Johnston; Male; 63; West Laurie-NM-75596; 2007-05-21
64; Anthony Thompson; Male; 61; North Kimberlyland-KS-29314; 2008-01-14
65; Mark Bolton; Male; 56; South Gregoryshire-OK-95787; 2015-01-26
66; Lauren Jackson; Male; 28; Erinport-DC-24100; 2020-01-10
67; Michael Martinez; Male; 52; Johnsontown-WV-62216; 2001-07-17
68; Lisa Klein; Male; 18; East Donnaview-CO-59190; 2002-01-30
69; Jacob Bryant; Male; 63; Fordville-TX-15969; 2004-01-10
70; Steven Taylor; Male; 43; Michaelchester-ND-78635; 2012-07-18
71; Rebecca Novak; Male; 22; West Kent-UT-78036; 2019-08-29
72; Victoria Robinson; Male; 35; Williamberg-NC-55183; 2015-12-20
73; Kathryn Maynard; Male; 31; South Stephaniefurt-RI-50950; 2000-10-05
74; Benjamin Casey; Male; 33; Ryanton-VT-38138; 2018-09-23
75; Grace Baird; Male; 77; Port Margaretland-TX-91596; 2014-06-08
76; Nicole Smith; Male; 79; New David-NM-78818; 2001-03-28
77; Evelyn Hawkins; Male; 37; Maddoxberg-IN-53455; 2007-01-20
78; Courtney Taylor; Male; 76; Martinview-NC-09759; 2015-01-21
79; Patricia Miller; Male; 50; West Kyleside-IL-28220; 2003-05-27
80; Crystal Schroeder; Male; 78; West Jakeborough-IL-38829; 2014-10-28
81; Tonya English; Male; 61; Julianhaven-MO-71886; 2017-04-07
82; Glen Martinez; Male; 23; Port Carrie-WA-49233; 2002-01-09
83; David George; Male; 53; Jeremiahmouth-WY-39655; 2021-07-08
84; Amber Jackson; Male; 80; Lake Joseph-KS-67884; 2009-02-04
85; Joshua Dillon; Male; 63; Lake Jeremiahmouth-MN-27122; 2006-11-20
86; Michael Dillon; Male; 59; Lake Karen-FL-33551; 2020-10-13
87; Richard Johnson; Male; 65; Samuelhaven-CT-85419; 2009-04-03
88; Adam Alvarado; Male; 20; East Jessicaside-AR-97225; 2019-04-15
89; Sally Madden; Male; 61; Davidburgh-VA-48355; 2020-07-10
90; Samantha Torres; Male; 49; North Nicholas-NE-18803; 2008-08-06
91; Mark Wilson; Male; 19; East Ashley-OH-14639; 2005-10-04
92; Mason Oliver; Male; 40; South Anthony-OH-81219; 2018-04-13
93; Ryan Garcia; Male; 35; North Christinaton-AK-37779; 2019-12-02
94; Joseph Peters; Male; 80; North Jillmouth-WV-09852; 2009-10-28
95; Casey Lawson; Male; 37; Bankstown-VT-74246; 2011-11-12
96; Daryl Jones; Male; 24; Lake Stephenshire-OR-54289; 2005-12-07
97; Robert Williams; Male; 26; Rachelmouth-SD-10847; 2021-08-08
98; Michael Ross; Male; 76; New Melissa-IL-76698; 2003-10-09
99; Jessica Smith; Male; 80; South Jessicafort-WV-07577; 2013-11-14
100; Melissa Smith; Male; 69; Juanton-AL-09499; 2002-06-18
101; Brandon Perkins; Male; 49; South Kevin-AL-22753; 2014-06-27
102; Tiffany Scott; Male; 55; Port Laurenfort-AR-39458; 2004-08-03
103; Robert Moss; Male; 61; Lake Carolynhaven-GA-90471; 2018-07-07
104; Adam Best; Male; 42; Robertburgh-ND-74118; 2005-09-26
105; Mary Lewis; Male; 38; Bakerside-VT-09314; 2000-03-14
106; Larry Moore; Male; 49; Morrisfort-CT-39434; 2003-06-14
107; Joshua Becker; Male; 24; North James-KY-83159; 2012-03-09
108; Jeffrey Douglas; Male; 58; New Roger-MN-03077; 2008-06-13
109; Elizabeth Bryant; Male; 24; West Eddieville-MO-92226; 2004-08-14
110; James Taylor; Male; 67; Watkinsmouth-GA-62362; 2012-01-15
111; Michael Hernandez; Male; 68; Port Loribury-GA-44661; 2012-12-11
112; Julie Johnston; Male; 43; North Davidtown-NJ-31820; 2021-04-24
113; Gregory Jacobs; Male; 45; North Bethany-ID-50560; 2015-07-27
114; Jonathon Morgan; Male; 33; West Jadeborough-HI-80516; 2016-04-21
115; Devin Wilson; Male; 50; North Amyview-NH-98941; 2004-11-19
116; Abigail Anderson; Male; 38; Ryanton-MA-91010; 2014-06-19
117; Sarah Ruiz; Male; 62; South Kimberly-NM-46995; 2021-03-18
118; Kimberly Farley; Male; 29; Smithport-CO-52676; 2015-02-01
119; Jennifer Galloway; Male; 61; Morrisberg-SC-33502; 2020-12-26
120; Tyler Morgan; Male; 71; Seanside-HI-54170; 2010-06-23
121; Victoria Wright; Male; 76; Michaelhaven-NV-29458; 2019-03-29
122; Nicholas Marks; Male; 20; Terryville-SD-23640; 2000-05-05
123; Angela Bishop; Male; 27; Port Cassandraland-TX-22224; 2011-04-14
124; Katherine Gonzalez; Male; 23; Joshuachester-WI-03800; 2017-07-03
125; Mrs. Holly Wall; Male; 75; East Geraldmouth-VT-83488; 2007-07-24
126; Amy Williams; Male; 41; Elizabethville-NC-63527; 2021-06-08
127; Ronald Yang; Male; 55; Lindsayborough-MS-19605; 2020-08-08
128; Eric Hines; Male; 37; Taylorstad-MI-93254; 2009-04-19
129; Holly Ross; Male; 23; West Natalie-MN-49836; 2001-12-22
130; Joshua Gonzalez; Male; 71; Goodmanbury-WY-60820; 2000-04-09
131; Kelly Owen; Male; 79; West Samantha-AK-72395; 2017-07-14
132; Tonya Anderson; Male; 52; Lake Johnberg-IN-11566; 2012-02-10
133; Gregg Lynn; Male; 22; Tracyside-NH-96440; 2016-09-11
134; Gary Dickson; Male; 63; Lake Samuelville-UT-63494; 2012-06-18
135; Barbara Navarro; Male; 56; Port Jamesshire-DC-02978; 2019-10-20
136; Erica Garcia; Male; 73; Donnashire-UT-18804; 2001-09-29
137; Deborah Finley; Male; 72; Hoodmouth-MA-45043; 2015-11-26
138; David Caldwell; Male; 25; Davidborough-MS-22340; 2005-10-22
139; Julian Smith; Male; 73; North Monica-CA-32308; 2013-07-28
140; Edward Carter; Male; 59; Webbton-CA-11637; 2004-02-21
141; James Day; Male; 73; Lauraburgh-SC-60909; 2020-10-18
142; Erika Hudson; Male; 39; Danielville-TN-53293; 2004-06-08
143; Ryan Holland; Male; 31; Josephside-NC-81119; 2013-11-20
144; Annette Lee; Male; 31; East Lisaport-MN-14318; 2005-11-03
145; Abigail Spencer; Male; 75; Crawfordview-WA-72704; 2005-03-05
146; James Ryan; Male; 38; Hodgesmouth-WV-41537; 2016-06-18
147; Brandon Gonzalez III; Male; 68; Lindaburgh-KY-76602; 2019-12-14
148; Lindsey Carpenter; Male; 48; Hudsonmouth-WY-98784; 2021-07-08
149; Kayla Massey; Male; 39; West Elizabeth-MT-09896; 2002-04-21
150; Bonnie Obrien; Male; 68; Fernandezstad-AL-23481; 2001-10-11
151; Mariah Griffith; Male; 23; New Deborah-AK-50640; 2018-12-12
152; Samuel Cruz; Male; 49; Jacquelineton-AZ-15554; 2009-12-05
153; Matthew Hoffman; Male; 62; West Dustin-DC-14108; 2010-01-16
154; Deanna Kemp; Male; 56; New Wayneview-ID-45022; 2004-06-16
155; Lauren Forbes; Male; 44; South Juan-VT-27018; 2001-02-21
156; David Garcia; Male; 29; Port Stuartmouth-UT-38814; 2016-05-07
157; Ashley Francis; Male; 78; Johnfort-SC-78659; 2005-07-25
158; Karen Randall; Male; 46; Shannonburgh-AZ-41276; 2012-09-20
159; Eric Martin; Male; 19; Katrinatown-MI-80510; 2008-08-14
160; Micheal Mueller; Male; 72; Schmidtport-NV-95549; 2019-08-06
161; Jacob Gilmore; Male; 53; New Cassandra-AL-01391; 2003-06-10
162; Elizabeth Anderson; Male; 54; Davidville-MD-12024; 2020-10-10
163; Elizabeth Kramer; Male; 80; Brookschester-KS-65550; 2019-07-01
164; Kathryn Alvarado; Male; 80; North Elizabeth-ME-38081; 2011-10-25
165; Audrey Livingston; Male; 28; South Sarahville-WA-09214; 2015-11-05
166; Richard Chen; Male; 48; Lawsonhaven-SD-50436; 2015-09-11
167; Robert Williams; Male; 72; New Elizabethbury-FL-60548; 2013-08-22
168; Adrienne Taylor; Male; 73; West Ethan-MS-37284; 2017-01-29
169; Matthew Cook; Male; 57; South Whitney-VA-96097; 2009-07-05
170; Stephanie Bush; Male; 28; Amyside-UT-49778; 2020-02-06
171; Ryan Johnson; Male; 27; New Julia-GA-71203; 2002-02-18
172; Nancy Medina; Male; 37; Port Donald-ME-67294; 2017-11-26
173; Lisa Neal; Male; 41; Mayside-WY-54084; 2001-01-31
174; Brandon Davis; Male; 22; Smithborough-SD-24502; 2013-04-21
175; James Pierce; Male; 65; Brownmouth-VA-06950; 2021-01-08
176; Heather Buchanan; Male; 21; Johnathantown-FL-33017; 2020-01-23
177; Patricia Johnson; Male; 70; East Caleb-ND-38308; 2002-12-31
178; Seth Sanford; Male; 73; Robertsshire-NM-93201; 2021-01-10
179; James Johns; Male; 34; Lake Crystalburgh-MD-99036; 2001-05-18
180; Kimberly Mason; Male; 26; Reedside-MN-89553; 2021-05-08
181; Patrick Gamble; Male; 71; Baileyville-MD-53563; 2016-10-14
182; Kimberly Bowen; Male; 35; Rushbury-NY-23974; 2011-01-15
183; James Evans; Male; 23; Gambleville-ID-78725; 2012-01-07
184; Shane Davis; Male; 79; East Devin-MO-24015; 2002-12-02
185; Bruce Morris; Male; 60; West Christineborough-AL-81962; 2008-11-09
186; Grant Soto; Male; 58; Port Patriciaside-MT-22954; 2008-02-04
187; Teresa Grimes; Male; 57; Gregoryview-AZ-22111; 2014-01-06
188; Thomas Jones; Male; 21; Hudsonfort-AZ-82313; 2019-03-14
189; Michael Booker; Male; 68; North Tracyton-MI-44184; 2002-09-26
190; Erica Moore; Male; 40; Baileyton-ND-38893; 2021-04-12
191; Gregory Barrera; Male; 19; Lake Tracy-TX-66785; 2015-11-04
192; Ryan Huerta; Male; 78; Port Kari-CO-24350; 2002-07-19
193; Nicole Kelly; Male; 32; East Travisfurt-IA-32556; 2018-11-26
194; Michael Marshall; Male; 20; Kellyhaven-OH-36909; 2013-11-12
195; Anthony Hunt; Male; 18; New Aaronview-SD-68573; 2004-02-24
196; Travis Mcconnell; Male; 73; Taylorborough-ND-34512; 2005-11-03
197; Evan Sanchez; Male; 67; New Brittanystad-KY-31604; 2014-11-23
198; Bobby Bradley; Male; 48; Desireeborough-NH-80201; 2016-07-07
199; Denise Davila DVM; Male; 41; North Francesview-OR-52784; 2019-01-10
200; Monica Burnett; Male; 18; Lake Kathytown-MD-65833; 2009-11-15
201; Derek Paul; Male; 22; Elizabethland-UT-52035; 2017-10-29
202; Amber Whitaker; Male; 38; Port Taylor-MT-09794; 2018-07-04
203; Brooke Edwards; Male; 55; Port Stacy-VT-66534; 2005-06-12
204; Christopher Watkins; Male; 40; West Jennifer-DC-27132; 2006-10-06
205; Connie Phillips; Male; 19; West Bradleyville-MD-45119; 2015-08-31
206; Lisa Davis; Male; 61; Castroport-NV-50660; 2003-02-26
207; Sara Rodriguez; Male; 28; Christopherside-MI-93045; 2005-03-13
208; Denise Hurley; Male; 51; Lake Dawnstad-DC-70492; 2013-09-29
209; Shannon Lee; Male; 30; Lindatown-IL-90511; 2016-06-18
210; Richard Adams; Male; 23; Cortezview-PA-83400; 2017-09-16
211; James Smith; Male; 69; North Thomasside-TX-87555; 2008-03-05
212; Eric Chang; Male; 70; Valenciaport-WY-83759; 2021-06-04
213; Amanda Miller; Male; 65; Pattersonton-WA-74933; 2011-03-03
214; Edwin Berger; Male; 23; East Kathleen-WI-76657; 2006-09-05
215; Jimmy Cooper; Male; 20; Zacharychester-OR-76998; 2001-10-29
216; Thomas Reed; Male; 21; Alvarezland-HI-01900; 2016-01-24
217; Karen Burke; Male; 50; Micheleville-MA-69176; 2007-10-28
218; Nancy Stark; Male; 19; Huangberg-DC-10157; 2018-11-09
219; John Moore; Male; 21; West Wendy-VT-04442; 2009-08-29
220; Mark Orozco; Male; 70; Riverachester-RI-38109; 2015-07-10
221; Javier Simmons; Male; 41; Lake Kristen-SC-27109; 2003-02-08
222; William Craig; Male; 41; Cruzfurt-HI-95004; 2015-05-16
223; Kimberly Anderson; Male; 48; West Cheryl-RI-48507; 2007-11-16
224; Michael Taylor; Male; 69; Rodriguezville-MI-12286; 2000-03-02
225; Kevin Morris; Male; 43; South Ashley-RI-91111; 2011-08-30
226; Andrea Chapman; Male; 53; Lake Margaretview-AR-88494; 2000-05-31
227; Christopher Young; Male; 40; North Dylanland-NM-28501; 2003-02-24
228; Ana Ashley; Male; 64; Jamesstad-WA-38437; 2010-04-04
229; Rachel Russell; Male; 54; Susanport-MN-64169; 2018-03-28
230; Sara Zavala; Male; 35; Grayfort-AK-01339; 2020-04-23
231; Jack Brown; Male; 58; Lake Belindafurt-DE-21537; 2004-08-01
232; Jerry Martinez; Male; 24; Christopherton-PA-60818; 2011-05-18
233; Donald Roy; Male; 33; Port Samanthaborough-ND-28155; 2005-11-24
234; Reginald Schmitt; Male; 29; West Priscilla-MI-84918; 2015-01-09
235; Janet Villarreal; Male; 75; New Xavierland-CO-75772; 2009-06-21
236; Andre Watkins; Male; 61; Margaretstad-CA-08454; 2003-10-14
237; Abigail Franco; Male; 50; Matthewfurt-MD-60998; 2004-06-02
238; Deborah Morton; Male; 71; Payneview-GA-22165; 2013-05-30
239; Mr. Dennis Waters MD; Male; 60; Bennettshire-HI-60588; 2007-07-08
240; Rebecca Scott; Male; 54; Deleonhaven-NE-33105; 2008-10-13
241; Trevor Adams; Male; 27; New Jaredton-WI-42230; 2014-12-02
242; Cameron Esparza; Male; 43; Anthonybury-MN-50386; 2008-12-21
243; Kathryn Dunn MD; Male; 41; Lake Tammyhaven-IA-88191; 2016-09-30
244; Julie Roberts; Male; 67; West Markport-MO-32971; 2004-10-23
245; Henry Reyes; Male; 64; West Thomas-IA-67234; 2007-05-09
246; Rachel Hernandez; Male; 46; Huberport-WV-37892; 2005-07-04
247; Rebecca Holloway; Male; 78; Garychester-PA-27894; 2020-02-10
248; Kimberly Fowler; Male; 71; South Elizabeth-VT-19411; 2010-05-23
249; William Scott; Male; 69; Robertchester-PA-18083; 2000-07-11
250; Brian Roach; Male; 63; South Nicole-MN-92366; 2017-10-27
251; Jacqueline Bailey; Male; 78; New Shelley-MI-21255; 2002-05-22
252; Brenda Smith; Male; 48; Garciamouth-NJ-06054; 2005-01-28
253; Kenneth Jones Jr.; Male; 23; New Daisychester-AZ-19191; 2003-02-18
254; Dominic Frazier; Male; 28; Tannerville-MT-77671; 2007-03-18
255; April Graham; Male; 78; Michaelborough-LA-77854; 2004-01-11
256; Cameron Lowe; Male; 74; Longside-MN-30881; 2006-07-12
257; Daniel Chambers; Male; 50; West Megan-NM-45647; 2018-03-12
258; Kristin Vargas; Male; 27; Jesseport-AR-85327; 2017-09-07
259; Brooke Miller; Male; 35; Tonibury-MA-40843; 2015-04-23
260; Frank Contreras; Male; 18; Hubbardtown-OK-01258; 2013-09-16
261; Mark Phillips; Male; 65; Karenview-AZ-08331; 2010-11-12
262; Lee Perez; Male; 35; Port Joseph-NJ-93532; 2012-10-19
263; Bradley Miller; Male; 53; Gallowayview-NJ-17545; 2005-03-24
264; Kimberly Sims; Male; 26; South Zacharystad-OH-53169; 2005-08-23
265; Michelle Yu; Male; 65; West Hannahmouth-AL-20283; 2020-11-30
266; Victoria Schmidt; Male; 53; Pattersonfort-VT-75539; 2007-07-25
267; Larry Brown; Male; 63; Mitchellfort-CA-29657; 2008-04-10
268; Katherine Zuniga; Male; 18; Frenchborough-MO-87222; 2015-05-19
269; Lauren Middleton; Male; 57; West Richardside-RI-21470; 2011-04-18
270; Anthony Rogers; Male; 39; Maryberg-UT-33645; 2000-05-29
271; Cheryl Simmons; Male; 31; South Michelleville-NE-73154; 2010-05-31
272; Dawn Walker; Male; 79; Ianchester-WI-07216; 2000-11-30
273; Teresa Terry; Male; 40; Webbfurt-NM-31603; 2000-04-12
274; Lynn Wheeler; Male; 29; Charleshaven-AZ-35635; 2009-04-14
275; Mary Wilcox; Male; 20; Lake Kevinstad-UT-68653; 2017-04-06
276; Alexandria Johnson; Male; 50; Monroehaven-OR-47139; 2021-09-30
277; Michael Trevino; Male; 33; Kennethshire-NE-51465; 2019-05-13
278; Amy Crawford; Male; 60; Port James-AZ-94727; 2001-09-24
279; Alex Davidson; Male; 27; Patrickland-IA-25945; 2004-08-16
280; Emily Harper; Male; 26; North Arthurbury-HI-22447; 2014-02-03
281; Cindy Alvarado; Male; 44; South Cassandra-NE-94926; 2000-08-28
282; Debbie White; Male; 62; Melissaport-CT-66021; 2021-09-23
283; Amanda Kemp; Male; 23; Smithfort-IN-87505; 2020-11-16
284; Benjamin Harrington; Male; 55; New Kimberlyfort-TN-68942; 2004-11-17
285; Jordan Kirk; Male; 53; Wallaceton-MA-28643; 2000-05-11
286; John Miller; Male; 33; West Mallory-LA-61944; 2006-06-03
287; Mark Duke; Male; 60; Ricardoshire-WA-91357; 2003-09-16
288; Seth Lopez; Male; 71; South Josephmouth-AL-62082; 2009-11-01
289; Robert White; Male; 47; Aimeetown-ME-59381; 2001-02-04
290; Teresa Pierce; Male; 31; Bullockfort-MD-79239; 2000-04-08
291; Jermaine Thornton; Male; 62; Port Seth-TN-81322; 2018-10-11
292; Carrie Lewis; Male; 53; Kellyport-MI-17866; 2018-04-28
293; Michael Edwards; Male; 58; West Samuel-NY-39834; 2017-09-26
294; Julie James; Male; 35; Port Wendybury-ND-21253; 2013-02-09
295; April Perez; Male; 68; Christopherfort-ME-18381; 2014-09-12
296; Vincent Brown; Male; 74; Jesusborough-ID-64244; 2006-04-13
297; William Hurley; Male; 80; Cummingston-DC-76262; 2011-01-20
298; Samantha Adkins; Male; 42; Granttown-AL-03975; 2010-06-17
299; Tiffany Richard; Male; 29; Lake Sarahhaven-DE-43443; 2002-05-13
300; Michael Walker; Male; 44; Williamchester-MO-57645; 2001-10-02
301; Mr. Jerry Mcintosh; Male; 18; New Amanda-MI-44982; 2001-10-02
302; Michael Andrews; Male; 40; North Brookeview-AL-34621; 2010-12-09
303; Jack Jensen; Male; 35; East Andrew-NV-96426; 2001-02-12
304; Kenneth Golden; Male; 79; Tylershire-GA-05137; 2012-11-22
305; Rebecca Hernandez; Male; 57; Port Jessicaland-DE-38511; 2018-08-20
306; Thomas Hammond; Male; 39; New Joseph-VA-22160; 2002-09-09
307; Terry Richardson; Male; 66; Jacksonport-HI-36369; 2018-08-15
308; Stephen Perry; Male; 72; Sarahchester-CO-32947; 2000-12-26
309; Jade Baxter; Male; 22; Lake Ryan-CO-95720; 2007-02-25
310; Julia Williams; Male; 64; Port Alexis-IN-06246; 2008-10-27
311; Stephanie Richardson; Male; 36; Lake Pamelaland-GA-14141; 2012-03-21

In [17]:
#question 2
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions



# Function to process the rows
def process_row(row):
    fields = next(csv.reader([row]))
    user_id, name, gender, age, address, date_joined = fields
    return gender



# Beam Pipeline for task 1
def run_pipeline():
    pipeline_options = PipelineOptions()
    with beam.Pipeline(options=pipeline_options) as p:
        input_data = (p
                      | 'Read CSV File' >> beam.io.ReadFromText('users_v (1).csv', skip_header_lines=1)
                      | 'Process Rows' >> beam.Map(process_row)
                      | 'Count Gender' >> beam.combiners.Count.PerElement()
                      #| 'Write to CSV' >> beam.io.WriteToText('marketing_format.csv', file_name_suffix='.csv', shard_name_template='')
                      | 'Print Results' >> beam.Map(print))
if __name__ == '__main__':
    run_pipeline()

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['-f', '/root/.local/share/jupyter/runtime/kernel-f060438b-38b1-4479-ad13-51b9f09726b6.json']

('male', 1207)
('female', 1150)

In [12]:
df = pd.read_csv('marketing_format.csv.csv')
df.head()

  1; Anthony Wolf; Male; 73; New Rachelburgh-VA-49583; 2019-03-13
0  2; James Armstrong; Male; 56; North Jillianfor...
1  3; Cody Shaw; Male; 75; North Anne-SC-53799; 2...
2  4; Sierra Hamilton; Male; 76; New Angelafurt-M...
3  5; Chase Davis; Male; 31; South Bethmouth-WI-1...
4  6; Sierra Andrews; Male; 21; Ryanville-MI-6969...

In [19]:
#question 3
# Function to process the rows

def process_row(row):

    fields = next(csv.reader([row]))

    user_id, name, gender, age, address, date_joined = fields

    return date_joined



# Beam Pipeline for task 1

def run_pipeline():

    pipeline_options = PipelineOptions()

    with beam.Pipeline(options=pipeline_options) as p:

        input_data = (p

                      | 'Read CSV File' >> beam.io.ReadFromText('users_v (1).csv', skip_header_lines=1)

                      | 'Process Rows' >> beam.Map(process_row)

                      | 'Count Date' >> beam.combiners.Count.PerElement()

                      | 'Print Results' >> beam.Map(print))



if __name__ == '__main__':

    run_pipeline()

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['-f', '/root/.local/share/jupyter/runtime/kernel-f060438b-38b1-4479-ad13-51b9f09726b6.json']

('2019/03/13', 1)
('2020/11/06', 1)
('2004/05/29', 2)
('2005/08/26', 1)
('2018/04/30', 1)
('2007/05/25', 1)
('2005/01/05', 2)
('2003/12/12', 2)
('2015/11/14', 1)
('2003/05/15', 1)
('2003/10/15', 2)
('2013/09/27', 2)
('2002/03/13', 1)
('2020/12/26', 3)
('2015/11/13', 1)
('2017/07/12', 1)
('2005/02/23', 2)
('2008/08/09', 1)
('2000/08/09', 1)
('2014/05/18', 2)
('2002/02/22', 1)
('2006/04/11', 1)
('2003/03/09', 1)
('2019/03/07', 2)
('2010/11/14', 1)
('2006/12/26', 1)
('2000/06/20', 2)
('2016/02/03', 2)
('2004/07/30', 2)
('2003/05/06', 1)
('2000/09/10', 1)
('2016/04/10', 1)
('2007/10/10', 1)
('2019/12/22', 1)
('2016/02/25', 1)
('2004/06/21', 2)
('2011/11/26', 1)
('2020/05/05', 1)
('2007/06/07', 1)
('2016/07/27', 2)
('2005/08/01', 1)
('2014/11/15', 2)
('2006/02/16', 2)
('2018/11/06', 1)
('2004/07/12', 1)
('2012/03/22', 1)
('2016/03/12', 2)
('2009/08/31', 1)
('2017/01/09', 1)
('2007/12/30', 1)
('2000/01/17', 1)
('2008/11/17', 2)
('2001/06/09', 1)
('2017/12/22', 2)
('2007/07/27', 1)
('2000/12/16', 2)
('2001/07/24', 1)
('2021/01/05', 2)
('2013/04/29', 2)
('2010/10/09', 2)
('2009/11/28', 2)
('2007/05/21', 1)
('2008/01/14', 1)
('2015/01/26', 3)
('2020/01/10', 1)
('2001/07/17', 1)
('2002/01/30', 1)
('2004/01/10', 1)
('2012/07/18', 1)
('2019/08/29', 1)
('2015/12/20', 1)
('2000/10/05', 1)
('2018/09/23', 1)
('2014/06/08', 1)
('2001/03/28', 1)
('2007/01/20', 1)
('2015/01/21', 1)
('2003/05/27', 1)
('2014/10/28', 1)
('2017/04/07', 1)
('2002/01/09', 1)
('2021/07/08', 2)
('2009/02/04', 1)
('2006/11/20', 2)
('2020/10/13', 1)
('2009/04/03', 2)
('2019/04/15', 1)
('2020/07/10', 2)
('2008/08/06', 1)
('2005/10/04', 1)
('2018/04/13', 1)
('2019/12/02', 2)
('2009/10/28', 1)
('2011/11/12', 2)
('2005/12/07', 1)
('2021/08/08', 1)
('2003/10/09', 1)
('2013/11/14', 2)
('2002/06/18', 1)
('2014/06/27', 1)
('2004/08/03', 1)
('2018/07/07', 1)
('2005/09/26', 1)
('2000/03/14', 1)
('2003/06/14', 2)
('2012/03/09', 1)
('2008/06/13', 1)
('2004/08/14', 2)
('2012/01/15', 1)
('2012/12/11', 2)
('2021/04/24', 1)
('2015/07/27', 2)
('2016/04/21', 2)
('2004/11/19', 2)
('2014/06/19', 1)
('2021/03/18', 2)
('2015/02/01', 1)
('2010/06/23', 2)
('2019/03/29', 2)
('2000/05/05', 1)
('2011/04/14', 1)
('2017/07/03', 1)
('2007/07/24', 1)
('2021/06/08', 1)
('2020/08/08', 1)
('2009/04/19', 1)
('2001/12/22', 1)
('2000/04/09', 1)
('2017/07/14', 1)
('2012/02/10', 1)
('2016/09/11', 1)
('2012/06/18', 1)
('2019/10/20', 1)
('2001/09/29', 1)
('2015/11/26', 1)
('2005/10/22', 2)
('2013/07/28', 1)
('2004/02/21', 1)
('2020/10/18', 1)
('2004/06/08', 1)
('2013/11/20', 1)
('2005/11/03', 2)
('2005/03/05', 1)
('2016/06/18', 2)
('2019/12/14', 1)
('2002/04/21', 1)
('2001/10/11', 3)
('2018/12/12', 1)
('2009/12/05', 1)
('2010/01/16', 1)
('2004/06/16', 1)
('2001/02/21', 1)
('2016/05/07', 1)
('2005/07/25', 1)
('2012/09/20', 1)
('2008/08/14', 1)
('2019/08/06', 1)
('2003/06/10', 1)
('2020/10/10', 1)
('2019/07/01', 1)
('2011/10/25', 2)
('2015/11/05', 1)
('2015/09/11', 1)
('2013/08/22', 1)
('2017/01/29', 1)
('2009/07/05', 1)
('2020/02/06', 1)
('2002/02/18', 1)
('2017/11/26', 1)
('2001/01/31', 1)
('2013/04/21', 1)
('2021/01/08', 1)
('2020/01/23', 1)
('2002/12/31', 2)
('2021/01/10', 1)
('2001/05/18', 1)
('2021/05/08', 1)
('2016/10/14', 1)
('2011/01/15', 1)
('2012/01/07', 1)
('2002/12/02', 1)
('2008/11/09', 1)
('2008/02/04', 1)
('2014/01/06', 1)
('2019/03/14', 1)
('2002/09/26', 1)
('2021/04/12', 1)
('2015/11/04', 1)
('2002/07/19', 1)
('2018/11/26', 2)
('2013/11/12', 1)
('2004/02/24', 1)
('2014/11/23', 1)
('2016/07/07', 1)
('2019/01/10', 1)
('2009/11/15', 1)
('2017/10/29', 1)
('2018/07/04', 1)
('2005/06/12', 2)
('2006/10/06', 1)
('2015/08/31', 2)
('2003/02/26', 1)
('2005/03/13', 1)
('2013/09/29', 1)
('2017/09/16', 1)
('2008/03/05', 1)
('2021/06/04', 1)
('2011/03/03', 1)
('2006/09/05', 2)
('2001/10/29', 1)
('2016/01/24', 1)
('2007/10/28', 1)
('2018/11/09', 1)
('2009/08/29', 1)
('2015/07/10', 1)
('2003/02/08', 1)
('2015/05/16', 3)
('2007/11/16', 1)
('2000/03/02', 1)
('2011/08/30', 1)
('2000/05/31', 1)
('2003/02/24', 2)
('2010/04/04', 1)
('2018/03/28', 1)
('2020/04/23', 1)
('2004/08/01', 1)
('2011/05/18', 1)
('2005/11/24', 1)
('2015/01/09', 1)
('2009/06/21', 1)
('2003/10/14', 1)
('2004/06/02', 1)
('2013/05/30', 2)
('2007/07/08', 1)
('2008/10/13', 2)
('2014/12/02', 1)
('2008/12/21', 1)
('2016/09/30', 1)
('2004/10/23', 1)
('2007/05/09', 2)
('2005/07/04', 2)
('2020/02/10', 1)
('2010/05/23', 1)
('2000/07/11', 2)
('2017/10/27', 1)
('2002/05/22', 1)
('2005/01/28', 1)
('2003/02/18', 2)
('2007/03/18', 1)
('2004/01/11', 1)
('2006/07/12', 3)
('2018/03/12', 1)
('2017/09/07', 1)
('2015/04/23', 1)
('2013/09/16', 1)
('2010/11/12', 1)
('2012/10/19', 1)
('2005/03/24', 1)
('2005/08/23', 1)
('2020/11/30', 1)
('2007/07/25', 2)
('2008/04/10', 1)
('2015/05/19', 1)
('2011/04/18', 1)
('2000/05/29', 1)
('2010/05/31', 1)
('2000/11/30', 2)
('2000/04/12', 1)
('2009/04/14', 1)
('2017/04/06', 1)
('2021/09/30', 1)
('2019/05/13', 1)
('2001/09/24', 2)
('2004/08/16', 1)
('2014/02/03', 3)
('2000/08/28', 1)
('2021/09/23', 2)
('2020/11/16', 1)
('2004/11/17', 1)
('2000/05/11', 1)
('2006/06/03', 1)
('2003/09/16', 1)
('2009/11/01', 1)
('2001/02/04', 1)
('2000/04/08', 1)
('2018/10/11', 1)
('2018/04/28', 1)
('2017/09/26', 1)
('2013/02/09', 1)
('2014/09/12', 1)
('2006/04/13', 1)
('2011/01/20', 2)
('2010/06/17', 1)
('2002/05/13', 1)
('2001/10/02', 2)
('2010/12/09', 1)
('2001/02/12', 1)
('2012/11/22', 2)
('2018/08/20', 2)
('2002/09/09', 1)
('2018/08/15', 2)
('2000/12/26', 2)
('2007/02/25', 1)
('2008/10/27', 1)
('2012/03/21', 2)
('2009/08/19', 1)
('2001/05/17', 1)
('2000/10/29', 1)
('2013/08/31', 1)
('2015/04/11', 2)
('2020/05/18', 1)
('2010/01/10', 1)
('2004/11/01', 1)
('2016/03/14', 1)
('2006/08/08', 1)
('2009/05/02', 1)
('2005/05/18', 1)
('2020/11/10', 1)
('2001/12/06', 1)
('2007/05/20', 2)
('2002/06/06', 1)
('2009/12/23', 1)
('2016/12/27', 1)
('2019/01/12', 2)
('2014/05/02', 1)
('2008/02/13', 1)
('2010/02/23', 1)
('2003/07/24', 1)
('2012/09/15', 1)
('2019/02/06', 2)
('2021/08/03', 1)
('2017/08/15', 1)
('2015/03/17', 1)
('2001/02/15', 2)
('2009/12/18', 1)
('2014/04/26', 1)
('2001/11/15', 2)
('2006/03/28', 1)
('2001/09/15', 1)
('2021/01/22', 1)
('2000/10/26', 1)
('2009/05/04', 1)
('2017/07/22', 1)
('2009/12/11', 1)
('2014/09/10', 1)
('2006/03/11', 2)
('2009/07/25', 2)
('2008/09/25', 1)
('2013/03/02', 3)
('2009/11/27', 1)
('2020/11/27', 1)
('2008/04/29', 1)
('2000/10/12', 1)
('2020/06/25', 1)
('2004/04/25', 1)
('2005/12/05', 2)
('2006/03/17', 1)
('2020/05/20', 1)
('2006/05/08', 2)
('2009/07/02', 1)
('2018/10/30', 1)
('2007/06/08', 1)
('2020/02/28', 1)
('2013/01/13', 1)
('2004/04/30', 1)
('2015/01/20', 1)
('2008/06/23', 2)
('2001/01/05', 1)
('2019/04/24', 2)
('2005/03/11', 1)
('2005/02/19', 1)
('2017/10/20', 1)
('2014/05/05', 1)
('2009/02/22', 1)
('2006/06/27', 1)
('2018/05/06', 1)
('2001/08/22', 1)
('2003/11/16', 1)
('2011/11/04', 1)
('2017/07/19', 1)
('2017/04/18', 2)
('2008/10/06', 1)
('2000/03/24', 2)
('2019/02/17', 3)
('2004/07/27', 2)
('2014/03/17', 1)
('2010/02/05', 1)
('2009/08/12', 1)
('2017/09/03', 1)
('2020/10/12', 2)
('2005/04/27', 1)
('2002/10/17', 3)
('2008/10/12', 2)
('2002/07/08', 3)
('2003/09/03', 1)
('2019/11/18', 1)
('2005/01/20', 2)
('2014/05/04', 1)
('2003/12/23', 1)
('2018/04/05', 1)
('2019/06/02', 1)
('2009/05/28', 1)
('2007/04/08', 1)
('2011/10/26', 2)
('2008/03/14', 1)
('2012/07/02', 2)
('2021/05/05', 1)
('2010/04/07', 2)
('2014/08/20', 2)
('2011/11/11', 1)
('2006/11/25', 1)
('2011/05/24', 1)
('2017/11/13', 1)
('2016/12/20', 1)
('2018/10/17', 5)
('2019/08/22', 1)
('2020/04/06', 1)
('2004/01/09', 1)
('2009/01/16', 1)
('2015/05/28', 1)
('2013/06/20', 1)
('2013/04/30', 1)
('2012/10/03', 1)
('2010/03/21', 1)
('2021/05/19', 1)
('2011/11/13', 1)
('2018/05/08', 1)
('2018/09/21', 1)
('2012/04/27', 1)
('2017/07/31', 1)
('2007/10/26', 1)
('2005/11/28', 1)
('2016/11/18', 1)
('2004/03/27', 1)
('2012/10/04', 1)
('2017/03/14', 1)
('2005/02/10', 1)
('2010/04/11', 1)
('2010/01/18', 1)
('2020/12/29', 1)
('2001/06/27', 1)
('2021/09/19', 1)
('2005/01/27', 1)
('2013/04/10', 1)
('2000/06/01', 1)
('2017/11/09', 1)
('2008/03/02', 1)
('2011/03/21', 1)
('2013/11/30', 2)
('2000/01/21', 1)
('2019/01/14', 2)
('2010/05/28', 1)
('2000/08/18', 1)
('2011/05/19', 1)
('2017/11/14', 1)
('2003/10/22', 1)
('2006/06/21', 1)
('2003/08/12', 1)
('2002/12/30', 2)
('2007/07/06', 1)
('2002/12/08', 1)
('2018/08/07', 1)
('2021/04/01', 1)
('2002/12/23', 1)
('2016/03/21', 2)
('2003/04/08', 1)
('2003/02/01', 1)
('2020/07/08', 1)
('2003/02/15', 1)
('2019/07/18', 2)
('2001/08/08', 1)
('2016/08/19', 1)
('2019/11/24', 1)
('2006/08/15', 1)
('2002/08/07', 2)
('2011/02/27', 1)
('2001/04/09', 3)
('2003/08/29', 1)
('2014/06/24', 1)
('2016/10/30', 1)
('2020/07/05', 1)
('2002/05/07', 1)
('2003/12/16', 1)
('2018/04/24', 3)
('2004/04/23', 2)
('2000/02/07', 2)
('2006/03/05', 3)
('2012/09/14', 1)
('2011/08/28', 1)
('2016/01/11', 1)
('2014/01/23', 1)
('2007/04/21', 2)
('2007/04/10', 1)
('2012/08/06', 1)
('2016/03/11', 1)
('2020/11/22', 2)
('2015/04/30', 1)
('2015/05/15', 1)
('2016/04/24', 1)
('2000/06/12', 1)
('2013/03/09', 1)
('2003/01/26', 1)
('2002/04/16', 1)
('2015/02/15', 1)
('2001/01/01', 2)
('2001/04/10', 1)
('2018/01/08', 2)
('2004/07/01', 2)
('2004/06/10', 1)
('2011/12/25', 2)
('2008/09/29', 1)
('2002/10/29', 1)
('2017/12/01', 1)
('2002/02/01', 1)
('2001/06/11', 1)
('2000/08/03', 2)
('2008/11/02', 1)
('2001/09/08', 1)
('2019/08/08', 1)
('2004/09/26', 1)
('2014/07/06', 1)
('2010/10/08', 1)
('2018/03/03', 1)
('2013/03/12', 1)
('2010/06/24', 1)
('2003/10/03', 1)
('2002/04/30', 1)
('2002/12/13', 1)
('2007/10/15', 1)
('2018/11/05', 1)
('2012/12/27', 1)
('2001/10/10', 1)
('2010/12/26', 1)
('2001/03/13', 1)
('2010/08/09', 1)
('2001/07/31', 1)
('2006/05/03', 2)
('2001/10/24', 3)
('2003/03/16', 1)
('2020/10/30', 1)
('2007/09/07', 1)
('2012/07/28', 1)
('2000/01/19', 1)
('2004/04/21', 1)
('2008/07/23', 1)
('2017/03/16', 1)
('2018/01/13', 1)
('2021/08/10', 1)
('2014/12/14', 1)
('2016/08/06', 2)
('2001/05/13', 1)
('2016/02/04', 1)
('2019/10/05', 2)
('2021/02/16', 1)
('2002/03/23', 1)
('2006/12/01', 1)
('2011/02/11', 3)
('2003/06/13', 1)
('2014/02/28', 1)
('2006/06/23', 1)
('2012/03/02', 1)
('2007/04/24', 1)
('2013/10/15', 1)
('2012/01/02', 1)
('2002/05/09', 1)
('2012/01/11', 1)
('2005/06/06', 1)
('2005/03/04', 1)
('2009/10/01', 2)
('2014/04/01', 1)
('2003/12/19', 1)
('2009/01/03', 1)
('2000/07/12', 1)
('2010/12/10', 1)
('2000/02/22', 1)
('2013/11/26', 1)
('2016/11/28', 1)
('2020/02/11', 1)
('2002/04/09', 1)
('2017/09/13', 1)
('2020/03/24', 1)
('2008/12/27', 1)
('2015/02/11', 2)
('2008/07/04', 1)
('2006/06/10', 1)
('2009/12/09', 1)
('2019/07/17', 1)
('2008/05/08', 1)
('2012/11/03', 1)
('2017/06/14', 1)
('2005/01/04', 1)
('2000/06/07', 1)
('2011/10/07', 1)
('2002/06/21', 1)
('2017/11/08', 2)
('2000/02/04', 1)
('2002/06/14', 1)
('2000/05/08', 1)
('2008/10/03', 1)
('2009/02/20', 1)
('2001/03/10', 1)
('2002/09/29', 1)
('2003/09/06', 1)
('2002/01/21', 2)
('2018/06/19', 1)
('2003/07/29', 1)
('2006/03/24', 1)
('2005/02/28', 1)
('2004/10/20', 2)
('2001/07/30', 2)
('2007/08/18', 1)
('2005/06/22', 1)
('2006/03/09', 1)
('2005/07/02', 1)
('2006/10/13', 1)
('2015/11/30', 1)
('2012/05/30', 2)
('2000/11/26', 1)
('2000/12/03', 1)
('2017/11/18', 1)
('2002/04/27', 1)
('2006/05/26', 1)
('2016/04/02', 1)
('2011/09/14', 2)
('2018/06/08', 1)
('2003/11/04', 1)
('2000/08/21', 1)
('2012/06/20', 1)
('2010/07/12', 1)
('2007/05/12', 2)
('2017/03/06', 2)
('2003/11/14', 1)
('2003/05/04', 1)
('2014/05/14', 1)
('2019/09/27', 1)
('2009/12/17', 1)
('2015/05/26', 1)
('2001/01/26', 2)
('2010/02/19', 2)
('2000/05/03', 2)
('2015/04/15', 1)
('2012/02/05', 1)
('2009/08/07', 1)
('2018/11/30', 2)
('2021/05/03', 1)
('2009/08/28', 1)
('2012/02/16', 1)
('2018/09/28', 1)
('2018/02/01', 1)
('2017/08/09', 1)
('2017/05/04', 1)
('2015/08/30', 1)
('2009/07/28', 1)
('2013/05/08', 1)
('2008/10/01', 1)
('2004/04/01', 1)
('2002/07/27', 1)
('2011/02/25', 1)
('2015/04/04', 1)
('2003/12/04', 1)
('2001/12/16', 1)
('2008/04/11', 1)
('2018/02/14', 2)
('2013/09/01', 2)
('2005/05/25', 1)
('2015/07/05', 1)
('2020/01/27', 1)
('2001/08/16', 1)
('2003/04/13', 1)
('2010/01/02', 1)
('2005/07/24', 1)
('2007/06/19', 1)
('2015/04/01', 1)
('2003/04/22', 1)
('2008/10/20', 1)
('2005/06/26', 1)
('2001/07/09', 1)
('2021/09/07', 1)
('2019/09/23', 1)
('2019/06/26', 1)
('2004/09/30', 1)
('2016/08/13', 1)
('2002/10/10', 2)
('2011/05/13', 4)
('2020/12/11', 1)
('2018/04/14', 1)
('2010/01/23', 2)
('2020/10/09', 1)
('2020/09/25', 1)
('2011/10/06', 1)
('2003/03/24', 1)
('2007/05/30', 1)
('2009/01/04', 1)
('2008/09/15', 1)
('2002/08/06', 1)
('2016/08/12', 1)
('2015/07/03', 1)
('2013/06/18', 1)
('2013/07/29', 1)
('2006/04/08', 1)
('2007/12/25', 2)
('2001/01/19', 2)
('2006/10/20', 1)
('2011/08/25', 1)
('2006/05/28', 1)
('2001/05/15', 1)
('2009/06/01', 1)
('2009/01/12', 1)
('2016/04/14', 2)
('2010/12/28', 2)
('2009/01/09', 1)
('2012/06/12', 2)
('2018/04/02', 1)
('2000/08/25', 1)
('2001/06/25', 1)
('2020/02/01', 1)
('2011/12/20', 1)
('2001/07/13', 1)
('2012/07/27', 2)
('2002/01/24', 1)
('2017/02/10', 1)
('2017/01/13', 1)
('2002/03/05', 1)
('2003/03/14', 1)
('2001/04/30', 1)
('2007/03/14', 1)
('2005/04/02', 2)
('2017/10/03', 1)
('2007/03/09', 2)
('2000/06/15', 1)
('2021/05/15', 1)
('2017/03/11', 1)
('2016/11/01', 1)
('2015/05/13', 1)
('2016/07/11', 1)
('2014/01/12', 2)
('2003/10/17', 1)
('2002/12/25', 1)
('2016/12/21', 1)
('2019/05/02', 1)
('2017/02/20', 1)
('2004/10/30', 1)
('2019/06/10', 1)
('2004/09/28', 1)
('2020/08/24', 1)
('2008/08/21', 1)
('2007/01/23', 3)
('2016/12/05', 1)
('2018/06/14', 1)
('2001/05/20', 1)
('2011/04/04', 2)
('2020/04/26', 1)
('2017/03/28', 2)
('2004/12/03', 1)
('2008/09/23', 1)
('2020/07/17', 1)
('2019/05/12', 1)
('2016/06/27', 1)
('2002/07/28', 1)
('2003/07/26', 1)
('2020/03/06', 1)
('2003/08/14', 1)
('2003/01/27', 2)
('2006/11/07', 1)
('2015/07/26', 1)
('2000/10/31', 1)
('2013/06/22', 1)
('2007/06/28', 1)
('2018/04/15', 1)
('2020/06/19', 1)
('2014/05/17', 1)
('2005/10/19', 1)
('2004/01/16', 1)
('2021/03/19', 2)
('2001/12/29', 1)
('2017/09/18', 2)
('2002/11/16', 1)
('2008/04/02', 1)
('2008/04/14', 1)
('2019/11/01', 1)
('2002/09/07', 1)
('2002/03/10', 1)
('2005/11/12', 1)
('2007/02/09', 1)
('2015/12/07', 1)
('2000/07/13', 1)
('2012/03/31', 1)
('2008/11/22', 1)
('2017/01/23', 1)
('2014/09/30', 1)
('2010/05/06', 1)
('2002/01/03', 1)
('2016/12/17', 1)
('2003/06/12', 1)
('2018/06/16', 2)
('2019/10/31', 1)
('2009/08/30', 1)
('2006/01/19', 1)
('2014/01/29', 2)
('2016/12/19', 1)
('2017/03/27', 1)
('2004/08/12', 1)
('2012/09/22', 2)
('2012/04/16', 2)
('2009/07/12', 1)
('2015/03/23', 1)
('2020/01/24', 1)
('2007/06/03', 1)
('2006/10/08', 1)
('2003/04/28', 2)
('2015/05/30', 1)
('2020/11/18', 1)
('2003/09/23', 1)
('2006/05/06', 1)
('2015/01/02', 2)
('2013/02/26', 1)
('2010/05/05', 1)
('2014/02/13', 1)
('2002/03/31', 1)
('2000/06/30', 1)
('2004/03/30', 1)
('2006/02/04', 2)
('2017/11/05', 1)
('2011/05/20', 1)
('2003/05/02', 1)
('2010/11/20', 1)
('2009/05/11', 1)
('2009/04/23', 1)
('2015/05/09', 1)
('2011/07/17', 1)
('2003/05/23', 1)
('2012/07/22', 1)
('2000/07/07', 1)
('2002/01/23', 1)
('2021/09/13', 1)
('2006/09/03', 2)
('2008/06/09', 1)
('2009/09/04', 2)
('2004/04/16', 1)
('2002/10/03', 1)
('2012/08/20', 1)
('2010/06/11', 1)
('2000/05/07', 1)
('2011/06/07', 1)
('2011/04/12', 1)
('2015/02/13', 1)
('2019/12/23', 1)
('2010/04/01', 2)
('2011/06/03', 1)
('2001/04/14', 1)
('2015/08/18', 1)
('2017/09/04', 2)
('2006/07/07', 1)
('2018/08/28', 1)
('2003/06/29', 1)
('2009/04/28', 2)
('2019/11/02', 1)
('2012/10/26', 1)
('2007/11/07', 1)
('2020/07/20', 1)
('2005/10/16', 1)
('2000/07/09', 1)
('2004/07/08', 1)
('2016/09/03', 1)
('2021/07/30', 1)
('2012/07/01', 1)
('2004/06/30', 2)
('2006/08/21', 1)
('2004/08/22', 1)
('2002/08/02', 2)
('2014/05/29', 2)
('2018/12/27', 1)
('2009/08/01', 1)
('2005/07/16', 1)
('2006/08/30', 1)
('2001/05/06', 1)
('2004/03/14', 1)
('2003/04/07', 2)
('2019/01/04', 2)
('2011/09/11', 2)
('2001/10/07', 1)
('2020/11/01', 1)
('2003/10/30', 1)
('2006/03/03', 1)
('2009/08/05', 1)
('2020/08/28', 1)
('2010/09/30', 1)
('2020/04/10', 2)
('2013/07/20', 1)
('2001/05/23', 1)
('2011/02/20', 1)
('2016/12/07', 1)
('2007/12/19', 1)
('2003/05/12', 1)
('2015/11/20', 3)
('2019/12/30', 1)
('2000/07/23', 1)
('2004/09/09', 1)
('2016/09/15', 1)
('2015/09/12', 1)
('2010/03/30', 1)
('2021/04/30', 1)
('2001/11/03', 2)
('2021/03/25', 1)
('2006/12/28', 2)
('2010/06/05', 1)
('2011/02/15', 1)
('2002/02/11', 1)
('2000/09/01', 2)
('2012/12/29', 2)
('2016/10/05', 1)
('2011/06/02', 1)
('2005/09/14', 1)
('2008/05/12', 1)
('2001/04/01', 1)
('2013/03/27', 1)
('2019/09/05', 1)
('2002/08/20', 2)
('2001/01/25', 1)
('2002/08/31', 1)
('2019/05/30', 1)
('2015/09/16', 1)
('2016/01/10', 1)
('2010/11/07', 2)
('2013/06/27', 1)
('2003/12/27', 1)
('2015/03/11', 1)
('2001/11/28', 2)
('2012/10/31', 2)
('2000/12/30', 1)
('2007/10/18', 1)
('2020/07/09', 1)
('2005/02/18', 1)
('2000/04/10', 1)
('2015/01/25', 1)
('2002/06/19', 1)
('2006/12/08', 1)
('2004/07/20', 1)
('2016/12/29', 1)
('2016/02/22', 1)
('2018/11/01', 1)
('2000/04/13', 2)
('2013/02/15', 1)
('2020/04/01', 1)
('2004/01/31', 2)
('2014/06/10', 2)
('2003/12/20', 1)
('2000/04/25', 1)
('2012/03/25', 1)
('2020/12/09', 2)
('2017/11/24', 1)
('2002/01/12', 1)
('2012/10/27', 1)
('2011/05/30', 1)
('2008/12/06', 1)
('2000/04/26', 1)
('2019/04/09', 1)
('2007/11/08', 1)
('2013/10/31', 2)
('2017/11/21', 2)
('2006/05/25', 2)
('2010/03/27', 1)
('2014/04/09', 1)
('2012/12/05', 2)
('2008/12/09', 2)
('2016/04/01', 1)
('2018/04/12', 1)
('2004/12/05', 1)
('2003/01/12', 1)
('2019/03/01', 3)
('2000/06/13', 1)
('2005/05/31', 1)
('2003/12/22', 2)
('2007/12/20', 1)
('2013/04/28', 1)
('2007/05/17', 2)
('2003/10/05', 1)
('2006/04/14', 2)
('2014/01/27', 1)
('2012/01/06', 2)
('2000/10/23', 1)
('2007/04/28', 1)
('2000/10/10', 1)
('2012/11/18', 2)
('2021/06/21', 1)
('2007/12/21', 1)
('2021/07/26', 2)
('2016/06/26', 1)
('2010/05/16', 1)
('2004/04/07', 1)
('2018/03/08', 1)
('2000/06/27', 1)
('2003/09/07', 1)
('2015/10/22', 1)
('2016/03/05', 2)
('2021/02/07', 1)
('2018/09/06', 1)
('2011/12/06', 1)
('2007/08/11', 1)
('2019/11/09', 1)
('2011/01/18', 1)
('2008/04/23', 1)
('2009/07/29', 1)
('2006/07/23', 2)
('2007/10/05', 2)
('2021/02/12', 1)
('2002/03/01', 1)
('2012/05/09', 1)
('2000/09/07', 1)
('2005/05/22', 1)
('2002/09/22', 1)
('2009/05/07', 1)
('2007/08/08', 1)
('2015/10/07', 1)
('2021/07/20', 1)
('2020/11/29', 1)
('2004/09/16', 2)
('2016/03/07', 1)
('2017/01/10', 1)
('2009/07/01', 1)
('2004/12/24', 1)
('2019/07/27', 1)
('2005/01/30', 1)
('2010/04/26', 1)
('2015/10/30', 1)
('2005/09/10', 1)
('2014/08/25', 1)
('2013/05/14', 1)
('2014/07/20', 1)
('2000/11/11', 1)
('2016/05/05', 1)
('2015/10/27', 1)
('2001/07/07', 1)
('2005/03/21', 3)
('2020/07/14', 2)
('2021/06/15', 1)
('2005/01/22', 1)
('2006/10/15', 1)
('2004/04/13', 1)
('2013/01/02', 1)
('2012/05/28', 2)
('2009/09/09', 1)
('2021/03/26', 1)
('2020/11/17', 1)
('2003/11/30', 3)
('2014/11/08', 1)
('2000/12/18', 1)
('2008/04/09', 1)
('2010/11/29', 1)
('2008/06/16', 1)
('2015/01/24', 1)
('2011/08/16', 1)
('2007/05/26', 2)
('2003/01/02', 2)
('2005/06/14', 1)
('2006/09/09', 1)
('2001/11/24', 1)
('2017/02/06', 1)
('2001/08/29', 1)
('2002/02/10', 1)
('2021/06/23', 1)
('2008/04/18', 2)
('2010/09/24', 1)
('2004/07/18', 1)
('2004/04/24', 1)
('2008/04/13', 1)
('2000/12/22', 1)
('2019/02/27', 1)
('2019/02/15', 1)
('2020/03/23', 1)
('2002/01/25', 2)
('2016/07/16', 1)
('2013/07/05', 1)
('2020/02/26', 1)
('2020/10/14', 1)
('2014/05/31', 1)
('2013/02/02', 1)
('2010/05/14', 3)
('2018/09/01', 1)
('2011/10/11', 1)
('2001/05/05', 1)
('2004/11/22', 1)
('2021/08/04', 1)
('2001/07/03', 1)
('2003/06/16', 1)
('2010/03/20', 1)
('2005/12/16', 1)
('2000/03/05', 1)
('2001/05/09', 1)
('2008/08/07', 1)
('2014/08/21', 2)
('2018/05/17', 1)
('2010/07/30', 1)
('2007/04/11', 1)
('2017/07/20', 1)
('2015/06/21', 1)
('2002/07/05', 1)
('2005/11/15', 2)
('2016/05/13', 1)
('2012/05/07', 1)
('2004/10/16', 1)
('2013/11/15', 1)
('2010/12/14', 1)
('2007/11/01', 1)
('2011/07/02', 2)
('2007/05/22', 1)
('2003/05/17', 1)
('2014/01/19', 1)
('2009/03/22', 1)
('2003/02/16', 1)
('2013/10/21', 1)

In [33]:
import apache_beam as beam
from apache_beam.options.pipeline_options import PipelineOptions
import csv



# Function to process the rows
def process_row(row):
    try:
        # Parse the row using comma as a delimiter
        fields = next(csv.reader([row], delimiter=','))
        # Ensure that there are exactly 6 fields before unpacking
        if len(fields) != 6:
            raise ValueError(f"Expected 6 fields, but got {len(fields)}: {fields}")

        user_id, name, gender, age, address, date_joined = fields
        # Split address by '-' and extract the state (second part)
        address_parts = address.split('-')
        state = address_parts[1].strip() if len(address_parts) > 1 else ''
        return state
    except Exception as e:
        # Print/log the error and return None for invalid rows
        print(f"Error processing row: {row}, Error: {e}")
        return None



# Beam Pipeline for task 1
def run_pipeline():
    pipeline_options = PipelineOptions()
    with beam.Pipeline(options=pipeline_options) as p:
        input_data = (p
                      | 'Read CSV File' >> beam.io.ReadFromText('users_v (1).csv', skip_header_lines=1)
                      | 'Process Rows' >> beam.Map(process_row)
                      # Filter out None values returned by invalid rows
                      | 'Filter None' >> beam.Filter(lambda x: x is not None)
                      | 'Count State' >> beam.combiners.Count.PerElement()
                      | 'Print Results' >> beam.Map(print))



if __name__ == '__main__':
    run_pipeline()

WARNING:apache_beam.options.pipeline_options:Discarding unparseable args: ['-f', '/root/.local/share/jupyter/runtime/kernel-f060438b-38b1-4479-ad13-51b9f09726b6.json']

('VA', 44)
('UT', 50)
('SC', 50)
('ME', 43)
('WI', 56)
('MI', 56)
('SD', 48)
('AK', 52)
('NJ', 58)
('VT', 54)
('NY', 45)
('AZ', 50)
('KY', 43)
('MT', 49)
('CT', 63)
('ID', 51)
('GA', 53)
('OR', 39)
('AR', 53)
('DC', 50)
('NC', 54)
('MA', 45)
('OH', 28)
('ND', 46)
('NM', 42)
('HI', 51)
('CA', 49)
('CO', 48)
('NH', 39)
('DE', 48)
('WY', 50)
('WA', 42)
('OK', 47)
('IN', 45)
('AL', 55)
('NV', 40)
('KS', 49)
('WV', 40)
('TX', 48)
('RI', 35)
('IL', 40)
('MO', 42)
('MN', 41)
('FL', 43)
('NE', 43)
('MS', 36)
('TN', 44)
('MD', 41)
('IA', 53)
('PA', 35)
('LA', 31)

In [23]:
#df = pd.read_csv('users_v (1).csv')
#df.head()

,user_id,name,gender,age,address,date_joined
0,1,Anthony Wolf,male,73,New Rachelburgh-VA-49583,2019/03/13
1,2,James Armstrong,male,56,North Jillianfort-UT-86454,2020/11/06
2,3,Cody Shaw,male,75,North Anne-SC-53799,2004/05/29
3,4,Sierra Hamilton,female,76,New Angelafurt-ME-46190,2005/08/26
4,5,Chase Davis,male,31,South Bethmouth-WI-18562,2018/04/30